export const skills = [
  {
    id: 0,
    title: "HTML",
    img: "/Assets/Images/html.png",
    competency: 98,
    color: "green",
  },
  {
    id: 1,
    title: "CSS",
    img: "/Assets/Images/css.png",
    competency: 80,
    color: "yellow",
  },
  {
    id: 2,
    title: "JS",
    img: "/Assets/Images/js.png",
    competency: 90,
    color: "orange",
  },
  {
    id: 3,
    title: "React JS",
    img: "/Assets/Images/react.png",
    competency: 93,
    color: "purple",
  },
  {
    id: 4,
    title: "Node JS",
    img: "/Assets/Images/node.png",
    competency: 85,
    color: "blue",
  },
  {
    id: 5,
    title: "Redux",
    img: "/Assets/Images/redux.png",
    competency: 96,
    color: "pink",
  },
  {
    id: 6,
    title: "Mongo DB",
    img: "/Assets/Images/mongodb.png",
    competency: 78,
    color: "teal",
  },
  {
    id: 7,
    title: "Python",
    img: "/Assets/Images/python.png",
  },
  {
    id: 8,
    title: "Django",
    img: "/Assets/Images/django.png",
  },
  {
    id: 9,
    title: "Flask",
    img: "/Assets/Images/flask.png",
  },
  {
    id: 10,
    title: "MySQL",
    img: "/Assets/Images/mysql.png",
  },
  {
    id: 11,
    title: "C",
    img: "/Assets/Images/C.png",
  },
  {
    id: 12,
    title: "Java",
    img: "/Assets/Images/java.png",
  },
  {
    id: 13,
    title: "Linux",
    img: "/Assets/Images/linux.png",
  },
];
